import Intl from "intl";

// export const timezones = [ ...new Set(Intl.supportedValuesOf('timeZone')
//   .map(tzl => Intl.DateTimeFormat("ia", {
//   timeZoneName: "short",
//   timeZone: tzl,
// }).formatToParts().find(o => o.type === "timeZoneName")?.value as string).filter(Boolean))];

export const timezones = [
  "GMT",
  "GMT+3",
  "GMT+1",
  "GMT+2",
  "HADT",
  "AKDT",
  "AST",
  "GMT-3",
  "GMT-4",
  "CST",
  "GMT-5",
  "MDT",
  "EST",
  "CDT",
  "MST",
  "GMT-7",
  "EDT",
  "ADT",
  "GMT-2",
  "PDT",
  "GMT-1",
  "GMT-2:30",
  "GMT+8",
  "GMT+7",
  "GMT+10",
  "GMT+11",
  "GMT+5",
  "GMT+13",
  "GMT+12",
  "GMT+4",
  "GMT+6",
  "GMT+5:30",
  "GMT+9",
  "GMT+4:30",
  "GMT+5:45",
  "GMT+6:30",
  "GMT+3:30",
  "GMT+10:30",
  "GMT+9:30",
  "GMT+8:45",
  "GMT+13:45",
  "GMT-6",
  "GMT-9",
  "HST",
  "GMT+14",
  "GMT-9:30",
  "GMT-11",
  "GMT-8",
  "GMT-10"
]
